### ISSUE TITLE
Support epub's as well as mobi's

### ISSUE THREAD

**Issue by lypanov** [christianhans/pinboard-to-kindle#12]
For future Kindle's may as well as move to epubs but for now could produce both based on a config option. Any thoughts about changing the default given Amazon's recent change of heart?

**Comment by christianhans** [comment]
That's a good idea and in fact a simple change.

**Comment by christianhans** [comment]
I think the only change needed would be [here](https://github.com/christianhans/pinboard-to-kindle/blob/master/process.sh#L24-L28) changing `.mobi` to `.epub`.

I do wonder however at what point in time this can be done. This article claims that epub support will come late this year:

https://www.engadget.com/amazon-kindle-supports-epub-format-002501848.html

So we may need to wait just a little bit?

**Comment by christianhans** [comment]
It looks like the Send to Kindle service already accepts epub format, so I changed the default format in https://github.com/christianhans/pinboard-to-kindle/commit/6786948ef88723fbb55bdd30f6512990a7c0cf99
